version: '2.1'
services:
  postgres:
    image: postgres
    env_file:
      - .env
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  memcached:
    image: memcached
    env_file:
      - .env
      - .env.development
    ports:
      - "11211"

  base:
    image: "${REGISTRY_HOST}${REGISTRY_URI}/base:latest"
    build:
      context: .
      dockerfile: Dockerfile.base

  web:
    build: .
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG:-master}"
    env_file:
      - .env
      - .env.development
    environment:
      VIRTUAL_HOST: hours.docker
      VIRTUAL_PORT: 80
    volumes:
      - .:/home/app/webapp
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    ports:
      - "${DOCKER_PORT}"
    depends_on:
      - postgres
      - memcached

volumes:
  postgres:
